### ISSUE TITLE
Unable to connect to my ESC/POS Printer through USB

### ISSUE THREAD

**Issue by eashaanbaberwal** [andrey-ushakov/esc_pos_printer#1]
The hostname has been hardcoded in the example where we require to know the IP address in advance, is there not a way to discover Existing printers and then connect with the device to execute the print commands?

Also is there not a method to detect ESC/POS printers with USB/Bluetooth?

**Comment by andrey-ushakov** [comment]
Hi,
To discover existing printers in your subnet you can use [ping_discover_network](https://pub.dev/packages/ping_discover_network) package. It's under active development and will be improved.
Note that most of ESC/POS printers by default listen on port 9100.

I will add USB/Bluetooth support a later but it's not my priority right now. Feel free to make a pull request if you wish to develop it ;)

Hope it helps!
