### ISSUE TITLE
esc_pos_printer ^4.0.3 is incompatible with flutter_cache_manager >=3.0.0-nullsafety

### ISSUE THREAD

**Issue by leutbounpaseuth** [andrey-ushakov/esc_pos_printer#105]
After upgrading to Flutter 2.0, we have an issue with package compatibility.
This issue affect also the package esc_pos_utils.

**Comment by wwandreww** [comment]
The package was updated to be compatible with Null-Safety. The libraries were updated too.
I'm closing this issue but feel free to reopen it if need.
I don't currently have a POS printer to test and support this plugin so your PRs are welcome!
