### ISSUE TITLE
Bluetooth support

### ISSUE THREAD

**Issue by JunioJsv** [andrey-ushakov/esc_pos_printer#11]
Pls implement Bluetooth support

**Comment by andrey-ushakov** [comment]
Hi,

I would like to do that but unfortunately I don't have any ESC/POS bluetooth printer to test. So it's nearly impossible to implement it for the moment...

**Comment by JunioJsv** [comment]
I can try to implement but I don't have the necessary knowledge yet, could you give me any tips? where to start

**Comment by andrey-ushakov** [comment]
I think you could try to use this lib: https://pub.dev/packages/flutter_bluetooth_serial

**Comment by andrey-ushakov** [comment]
I'm going to close this issue, feel free to reopen it if need

**Comment by andrey-ushakov** [comment]
Hi @JunioJsv ,
The package now supports Bluetooth printers **in beta mode**.

**Comment by JunioJsv** [comment]
@andrey-ushakov Thank you, already have the documentation available?

**Comment by JunioJsv** [comment]
![Captura de Tela (31)](https://user-images.githubusercontent.com/39963398/72485701-574f2880-37e7-11ea-8bb2-bc41a48c02f2.png)
I tried searching for devices and this error occurred, on Lineage OS Android Pie. I will test on another device.

**Comment by JunioJsv** [comment]
2020-01-15 23:34:24.381 28100-28117/juniojsv.bem_servir_comanda I/flutter: Error starting scan.
2020-01-15 23:34:24.441 28100-28117/juniojsv.bem_servir_comanda E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method startScan on channel flutter_bluetooth_basic/methods)
    #0      BluetoothManager.scan (package:flutter_bluetooth_basic/src/bluetooth_manager.dart:85:7)
    <asynchronous suspension>
    #1      BluetoothManager.startScan (package:flutter_bluetooth_basic/src/bluetooth_manager.dart:116:11)
    #2      PrinterBluetoothManager.startScan (package:esc_pos_printer/src/printer_bluetooth_manager.dart:47:23)
    #3      AppModel.searchPrinters.<anonymous closure> (package:bem_servir_comanda/models/app_model.dart:17:25)
    #4      Builder.build (package:flutter/src/widgets/basic.dart:6834:41)
    #5      StatelessElement.build (package:flutter/src/widgets/framework.dart:4392:28)
    #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4324:15)
    #7      Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
    #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4307:5)
    #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4302:5)
    #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
    #11     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
    #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
    #13     Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
    #14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4307:5)
    #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4302:5)
    #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
    #17     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
    #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
    #19     Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
    #20     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4307:5)
    #21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4302:5)
    #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
    #23     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
    #24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5570:14)
    #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
    #26     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
    #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
    #28     Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
    #29     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4307:5)
    #30     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4302:5)
    #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
    #32     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
    #33     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5570:14)
    #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
    #35     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
    #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
    #37     Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
    #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4307:5)
    #39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4302:5)
    #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
    #41     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
    #42     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5570:14)
    #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
    #44     Element.updateChild (package:flutter/src/wid

**Comment by JunioJsv** [comment]
Realize now that the bluetooth function only works on iOS for now, right? You had to make that clear in README.md, I found this information in pub.dev Changelog

**Comment by andrey-ushakov** [comment]
Hi @JunioJsv ,
Thank you for your feedback. It's already clearly stated in README.md :)
BTW, I hope Android support will be added soon as well.

**Comment by andrey-ushakov** [comment]
Hi,
I've just added Android support :)
Feel free to re-open this issue if need.

**Comment by andrey-ushakov** [comment]
Hi @JunioJsv ,

Does the library work well for you?
I've created a [list of printers tested with this library](https://github.com/andrey-ushakov/esc_pos_printer/blob/master/printers.md). 

May I ask you to add your printer model into the table?
It will help me to maintain the library and others to choose the right printer!
Thank you!

**Comment by shajin-screl** [comment]
is android platform channel ready to use? 

or still only IOS is currently offered?
