### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by niktses** [andrey-ushakov/esc_pos_printer#110]

**Comment by anik786** [comment]
Someone made a pull request for this:
https://github.com/andrey-ushakov/esc_pos_printer/pull/113

**Comment by wwandreww** [comment]
The package was updated to be compatible with Null-Safety. The libraries were updated too.
I'm closing this issue but feel free to reopen it if need.
I don't currently have a POS printer to test and support this plugin so your PRs are welcome!
