### ISSUE TITLE
esc_pos_printer Error while pub get 

### ISSUE THREAD

**Issue by abdulrehmananwar** [andrey-ushakov/esc_pos_printer#117]
Because esc_pos_printer >=4.0.0 depends on image ^2.1.4 and esc_pos_utils_plus 2.0.1+3 depends on image ^3.0.1, esc_pos_printer >=4.0.0 is incompatible with esc_pos_utils_plus 2.0.1+3.
And because no versions of esc_pos_utils_plus match >2.0.1+3 <3.0.0, esc_pos_printer >=4.0.0 is incompatible with esc_pos_utils_plus ^2.0.1+3.
So, because tag depends on both esc_pos_utils_plus ^2.0.1+3 and esc_pos_printer ^4.0.3, version solving failed.
pub get failed (1; So, because tag depends on both esc_pos_utils_plus ^2.0.1+3 and esc_pos_printer ^4.0.3, version solving failed.)

bleow is doctor -v
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
    • Flutter version 2.0.6 at E:\flutter_windows_2.0.6-stable\flutter
    • Framework revision 1d9032c7e1 (2 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\hp\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 16.0.1+9-24)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 84.0.522.52

! Doctor found issues in 2 categories.

**Comment by wwandreww** [comment]
The package was updated to be compatible with Null-Safety. The libraries were updated too.
I'm closing this issue but feel free to reopen it if need.
I don't currently have a POS printer to test and support this plugin so your PRs are welcome!
