### ISSUE TITLE
can support bluetooth?

### ISSUE THREAD

**Issue by live17909** [andrey-ushakov/esc_pos_printer#12]
can support bluetooth?

**Comment by andrey-ushakov** [comment]
Hi,

No, only USB is supported for the moment

**Comment by ccfiel** [comment]
> Hi,
> 
> No, only USB is supported for the moment

Is usb supported now?

**Comment by andrey-ushakov** [comment]
Hi @live17909,
The package now supports Bluetooth printers **in beta mode**.
