### ISSUE TITLE
Is the package still maintained??

### ISSUE THREAD

**Issue by emme1009** [andrey-ushakov/esc_pos_printer#125]
So many issues are open till months and not one single response of the author ?

Does someone has any informations or any alternative packages that we can use in production without those issues ?

**Comment by dsingh06** [comment]
I am in the same boat. There needs to be an alternative, this package has been great but it seems it is not being maintained anymore. Null-Safety upgrade is long due

**Comment by amit-onappr** [comment]
This is great plugin and sadly no alternative is available. @andrey-ushakov let us know if this being managed or some helping hands needed?

**Comment by farellsujanto** [comment]
Me too. I need esc package in my project, but there is no alternative to this one. A lot of update & maintenance needed for this one.

**Comment by emmaxCreative** [comment]
Still no reaction of the author 👎  @andrey-ushakov can we please have a statement of you?...
I guess a lot of users are stuck because of these mostly minor bugs that stops them from using an otherwise awesome package..

**Comment by jobypthomas** [comment]
Any alternative package to this for flutter? This seems work but dated.

**Comment by emmaxCreative** [comment]
I use this fork which at least solves some minor issues 
https://github.com/CastawayLabs/dart-escpos

Still a shame that there is not a single reaction from the author...

**Comment by wwandreww** [comment]
The package was updated to be compatible with Null-Safety. The libraries were updated too.
I'm closing this issue but feel free to reopen it if need.
I don't currently have a POS printer to test and support this plugin so your PRs are welcome!
