### ISSUE TITLE
when I print my invoice image, the result of printer just take only half of paper width

### ISSUE THREAD

**Issue by kechankrisna** [andrey-ushakov/esc_pos_printer#13]
I used your package to print, almost everything works fine but one thing that I can't complete which is: when I print my invoice image, the result of printer just take only half of paper width, it didn't take the full width of paper.

**Comment by kechankrisna** [comment]
Is there any idea or solution that I can do, please let me know. Thank you in advance.

**Comment by andrey-ushakov** [comment]
Hi,

I think the easiest way would be just to resize the image before printing.

**Comment by kechankrisna** [comment]
Thank you for your response, I did resize to fit the page by just 272 pixel, but it seems like all printing image just take only half of the paper width. I also did resize to make it to be bigger, but got the same result.

**Comment by kechankrisna** [comment]
But when I change  highDensityHorizontal to true and highDensityVertical to true in printImage() method, I get full width printing, but another issue has happened, which is the texts printed are not clear, it was a bit bold and dark.

**Comment by andrey-ushakov** [comment]
So any image takes exactly a half of the width? I would say it should depend on image width/height ratio but unfortunately I can't test it as I don't have a POS printer right now... There are chances that it also depends on a printer's brand.

For the unclear printing with highDensity = true, did you try to print a high-resolution image? Does it resolve the issue?

**Comment by kechankrisna** [comment]
Yes, I did test it by using the same image I printed with browser. but the quality of image I printed using browser is better quality than. It is cleared text.

**Comment by kechankrisna** [comment]
Here the result of what I tested with image captured with width of 270px. [image](blob:https://web.telegram.org/e434312d-a107-4dd6-830a-cb107dcd8728)

**Comment by HTipi** [comment]
Hi bro@kechankrisna 

Could you help share the printer model details?
Thank in advance

**Comment by andrey-ushakov** [comment]
Hi @kechankrisna 

I finally have time and a pos printer to test the issue you have described.
If you can share your image and the exact code, I can test it on my device and fix the problem.
As far I can see from your image, you are using a 160mm paper and this lib was developed for a 80mm printer. Probably the easiest way (but definitely not the best) is to add a parameter in future releases to define the paper size.

**Comment by kechankrisna** [comment]
I am sorry for being late to reply on this problem, I found the solution now, by change picture width to 570px while I also changed highDensityHorizontal to true and highDensityVertical to true for printImage() function. My printer model is X-Printer xp-n160ii printer.

**Comment by ul-rotha** [comment]
do you have sample code print our khmer unicode to thermal printer?

**Comment by kechankrisna** [comment]
> do you have sample code print our khmer unicode to thermal printer?

try to print as image bro

**Comment by ul-rotha** [comment]
how to write receipt as image bro?

**Comment by kechankrisna** [comment]
you can use any plugin to capture widget to image. This package can be found in pub or I created one too.

**Comment by ul-rotha** [comment]
image so small after capture screen and pass to ticket.image(image);
[
![124811781_410621290318329_8194284614197584876_n](https://user-images.githubusercontent.com/51068059/98650252-386be500-236b-11eb-9cbe-c0f799774bce.jpg)
](url)

**Comment by kechankrisna** [comment]
change picture width to 570px so that would be enough

**Comment by ul-rotha** [comment]
could you link url code for changing picture width? i could not found

**Comment by kechankrisna** [comment]
Here is a sample:
`
  final Ticket ticket = Ticket(PaperSize.mm58);
  final Image image = decodeImage(file.readAsBytesSync());
  final Image thumbnail = copyResize(image, width: 572);
  ticket.image(thumbnail);
`

**Comment by ul-rotha** [comment]
thank you brother it works.

**Comment by ul-rotha** [comment]
do you have problem like me when we have long receipt , printer can not print successful and not cutting paper?

**Comment by kechankrisna** [comment]
> do you have problem like me when we have long receipt , printer can not print successful and not cutting paper?

Sure, that is the reason i clone this repo and update a new one which delay and chunk.

**Comment by ul-rotha** [comment]
how to solve this problem bro?

**Comment by kechankrisna** [comment]
> how to solve this problem bro?
Here is my package that i customize from: https://pub.dev/packages/flutter_esc_printer. Hope it will help you to solve your problems bro.

**Comment by ul-rotha** [comment]
> > how to solve this problem bro?
> > Here is my package that i customize from: https://pub.dev/packages/flutter_esc_printer. Hope it will help you to solve your problems bro.

Thank you so much for you help bro

**Comment by kechankrisna** [comment]
> > > how to solve this problem bro?
> > > Here is my package that i customize from: https://pub.dev/packages/flutter_esc_printer. Hope it will help you to solve your problems bro.
> 
> Thank you so much for you help bro

you are welcome :D

**Comment by ul-rotha** [comment]
bro how can we capture widget to image on runtime without preview page?

**Comment by ul-rotha** [comment]
> you can use any plugin to capture widget to image. This package can be found in pub or I created one too.
> https://pub.dev/packages/flutter_screenshot

Brother when i have long height widget i screenshot error. it throw Exception: operation failed. do you have this problem?

**Comment by YouSour** [comment]
hi , how can you guy solve this problem ? this package look like outdated  [https://pub.dev/packages/flutter_esc_printer](https://pub.dev/packages/flutter_esc_printer) which package you're using right now ?
