### ISSUE TITLE
Is there an intention to maintain this package?

### ISSUE THREAD

**Issue by dsingh06** [andrey-ushakov/esc_pos_printer#133]

**Comment by emmaxCreative** [comment]
#125 I dont think so...we never get a response from the author

**Comment by wwandreww** [comment]
The package was updated to be compatible with Null-Safety. The libraries were updated too.
I'm closing this issue but feel free to reopen it if need.
I don't currently have a POS printer to test and support this plugin so your PRs are welcome!

**Comment by nicks258** [comment]
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:ping_discover_network
 - package:wifi
 Facing issue while running example project
