### ISSUE TITLE
Image printing

### ISSUE THREAD

**Issue by masiJR** [andrey-ushakov/esc_pos_printer#14]
Uint8List bytes = Uint8List.fromList(list).buffer.asUint8List();
final Image image1 = decodeImage(bytes);
printer.printImage(image1); 

Error: 
NoSuchMethodError: The getter 'width' was called on null.

**Comment by andrey-ushakov** [comment]
Hi @masiJR ,

Sorry for the late reply
Did you resolve the issue? What was the problem?

If you are still facing the issue, please share us the exact image you are printing, your printer model and the package version.

Thank you

**Comment by andrey-ushakov** [comment]
Hi @masiJR ,

Does the library work well for you?
I've created a [list of printers tested with this library](https://github.com/andrey-ushakov/esc_pos_printer/blob/master/printers.md). 

May I ask you to add your printer model into the table?
It will help me to maintain the library and others to choose the right printer!
Thank you!
