### ISSUE TITLE
can you add support bluetooth?tks

### ISSUE THREAD

**Issue by kevin-lr** [andrey-ushakov/esc_pos_printer#15]

**Comment by andrey-ushakov** [comment]
Hi @kevin-lr,
Sorry, I don't have a bluetooth pos printer to develop and test. So this feature is not my priority...

**Comment by CameronSima** [comment]
I'd be interested in this as well, and would like to work on it. Any pointers on how to substitute out the Socket connection for a Bluetooth interface using flutter_blue? Any pointers would be greatly appreciated

**Comment by andrey-ushakov** [comment]
Hi @kevin-lr and @CameronSima ,
The package now supports Bluetooth printers **in beta mode**.

**Comment by andrey-ushakov** [comment]
Hi @kevin-lr and @CameronSima ,

Does the library work well for you?
I've created a [list of printers tested with this library](https://github.com/andrey-ushakov/esc_pos_printer/blob/master/printers.md). 

May I ask you to add your printer model into the table?
It will help me to maintain the library and others to choose the right printer!
Thank you!
