### ISSUE TITLE
 Align bar code or margins

### ISSUE THREAD

**Issue by Ohpizarro** [andrey-ushakov/esc_pos_printer#16]
Possibility of setting the margin before printing the bar code or allowing left, center or right alignment.
Thank you for your development.

**Comment by andrey-ushakov** [comment]
Hi @Ohpizarro , really good feature, thanks! I'll try to implement it in a next release.
If you already have a solution or wish to help, feel free to make a pull request!

**Comment by andrey-ushakov** [comment]
I've just added this feature :)

Now images and barcodes are centered by default, but you can also pass the `align` parameter for left/right alignment.

BTW, the `PosTextAlign` enum renamed to `PosAlign`. You have to rename it in your code if you are using it somewhere.

I hope it helps!

I'm going to close this issue, but feel free to reopen it if you have any further questions or ideas!

**Comment by Ohpizarro** [comment]
Very grateful for your time in answering my question. Thanks for your code,
it helped me a lot in my first app.
