### ISSUE TITLE
Print showing '00' character in front of the word

### ISSUE THREAD

**Issue by HCID-SMART** [andrey-ushakov/esc_pos_printer#17]
Hi @andrey-ushakov,

First of all, thanks for making this plugin. this is really useful.

I have a question about this plugin.
When i print a simple text, there's always an added '00' text in front of the text that i wanted to print. Example:
![WhatsApp Image 2019-10-28 at 20 56 28](https://user-images.githubusercontent.com/56336855/68295982-24413800-00c6-11ea-8e06-8c1b54081c61.jpeg)

Can you help me on this? because i really have no idea.
Thanks.

Here is the code that i use to print the above image:

` Printer.connect(prefs.getString('printer-ip-1'), port: 9100).then((printer) {
      printer.println('This is a test print');
      printer.println('Special 1: àÀ èÈ éÉ ûÛ üÜ çÇ ôÔ',
          styles: PosStyles(codeTable: PosCodeTable.westEur));
      printer.println('Special 2: blåbærgrød',
          styles: PosStyles(codeTable: PosCodeTable.westEur));

      printer.println('Bold text', styles: PosStyles(bold: true));
      printer.println('Reverse text', styles: PosStyles(reverse: true));
      printer.println('Underlined text',
          styles: PosStyles(underline: true), linesAfter: 1);

      printer.println('Align left', styles: PosStyles(align: PosTextAlign.left));
      printer.println('Align center',
          styles: PosStyles(align: PosTextAlign.center));
      printer.println('Align right',
          styles: PosStyles(align: PosTextAlign.right), linesAfter: 1);

      printer.printRow([
        PosColumn(
          text: 'col3',
          width: 3,
          styles: PosStyles(align: PosTextAlign.center, underline: true),
        ),
        PosColumn(
          text: 'col6',
          width: 6,
          styles: PosStyles(align: PosTextAlign.center, underline: true),
        ),
        PosColumn(
          text: 'col3',
          width: 3,
          styles: PosStyles(align: PosTextAlign.center, underline: true),
        ),
      ]);

      printer.println('Text size 200%',
          styles: PosStyles(
            height: PosTextSize.size2,
            width: PosTextSize.size2,
          ));

      printer.cut();
      printer.disconnect();
    });`

**Comment by andrey-ushakov** [comment]
Hi @HCID-SMART ,

Sorry for the delayed reply.
Did you resolve the issue?

Probably your POS printer implements a slightly different ESC/POS protocol. I suspect the text reverse command.

First of all, try to remove the line 99 in the lib/src/printer.dart file: 
`_socket.write(styles.reverse ? cReverseOn : cReverseOff);`

And print a test ticket again. Does it help?

**Comment by FrankSantoso** [comment]
Hi, I'm having the same issue, and i can't find the specific line mentioned above in this repo.

Appreciate any feedback, great job @andrey-ushakov

**Comment by andrey-ushakov** [comment]
Hi @HCID-SMART and @FrankSantoso,

Are you still facing the same issue? What are your printer models, please?
Thanks

**Comment by andrey-ushakov** [comment]
Hi @HCID-SMART,
I've recently updated the library. It may fix your issue.
May I ask you to print a few test tickets using your printers to check if it helps, please?
