### ISSUE TITLE
Error Unhandled Exception: Invalid argument (string): Contains invalid characters.: "ใบเสร็จ-ใบรับผ้า"

### ISSUE THREAD

**Issue by kmochimaru** [andrey-ushakov/esc_pos_printer#19]
How to config charset UTF-8 (Thai) please ?

**Comment by andrey-ushakov** [comment]
Hi,
Please check this issue : #18

**Comment by kmochimaru** [comment]
I want to use pc874 but PosCodeTable is noting. I try to modify library set code page 255 or 70 It's not working. I use Xprinter XP-Q200

**Comment by kmochimaru** [comment]
Code page detail about thermal printer
![IMG_3272](https://user-images.githubusercontent.com/21367818/69704534-2e36e380-1126-11ea-9ec5-0a194e062bb6.jpg)

**Comment by andrey-ushakov** [comment]
Hi,
Now it should be possible to print Thai texts, here are some examples for other languages:
https://github.com/andrey-ushakov/esc_pos_printer#using-code-tables
I hope this helps!

Feel free to reopen the issue if you have any further questions

**Comment by amibappy** [comment]
@kmochimaru 

Did you find any solution?
I am having the same problem with Japanese characters.
Please share if you have found any solution.
