### ISSUE TITLE
Can't support chinese font

### ISSUE THREAD

**Issue by raindy29** [andrey-ushakov/esc_pos_printer#2]
printer.println('中文字');

**Comment by raindy29** [comment]
I solved this issues, please add the code

commands.dart 
`const cChineseMode = '${fs}&'; // Chinese Mode`

printer.dart
`  void chineseln(
      String text, {
        PosStyles styles = const PosStyles(),
        int colInd = 0,
        int linesAfter = 0,
        String code = 'big5',  // big5 or gbk
      }) {
    final int pos = colInd == 0 ? 0 : (512 * colInd / 11 - 1).round();
    final hexStr = pos.toRadixString(16).padLeft(3, '0');
    final hexPair = HEX.decode(hexStr);

    _socket.write(styles.bold ? cBoldOn : cBoldOff);
    _socket.write(styles.turn90 ? cTurn90On : cTurn90Off);
    _socket.write(styles.reverse ? cReverseOn : cReverseOff);
    _socket.write(styles.underline ? cUnderline1dot : cUnderlineOff);
    _socket.write(styles.align == PosTextAlign.left
        ? cAlignLeft
        : (styles.align == PosTextAlign.center ? cAlignCenter : cAlignRight));
    _socket.write(styles.fontType == PosFontType.fontA ? cFontA : cFontB);
    // Text size
    _socket.add(
      Uint8List.fromList(
        List.from(cSizeGSn.codeUnits)
          ..add(PosTextSize.decSize(styles.height, styles.width)),
      ),
    );
    // Position

    _socket.add(
      Uint8List.fromList(
        List.from(cPos.codeUnits)..addAll([hexPair[1], hexPair[0]]),
      ),
    );

    // Set local code table
    if (styles.codeTable != null) {
      _socket.add(
        Uint8List.fromList(
          List.from(cCodeTable.codeUnits)..add(styles.codeTable.value),
        ),
      );
    }

    _socket.write(cChineseMode);
    if (code == 'big5') {
      _socket.add(big5.encode(text));
    } else {
      //_socket.add(gbk.encode(text));
    }
    _socket.write(cKanjiCancel);

    _socket.writeln();
    emptyLines(linesAfter);
    reset();
  }`

**Comment by andrey-ushakov** [comment]
Hi,

Many thanks for your solution !!
I'm going to test that and potentially add in the lib a bit later.

Have a nice day!

**Comment by andrey-ushakov** [comment]
Hi,
Now it's possible to print mixed Chinese/Non-Chinese text using **printlnMixedKanji** method: 

```dart
// Print mixed (chinese + latin) text. Only for printers supporting Kanji mode
printer.printlnMixedKanji(
    'hello ! 中文字 # world @ éphémère &',
    styles: PosStyles(codeTable: PosCodeTable.westEur),
);
```

**Comment by andrey-ushakov** [comment]
I'm going to close this issue, but feel free to reopen it if there is something to improve.

**Comment by andrey-ushakov** [comment]
Hi @raindy29,

Does the library work well for you?
I've created a [list of printers tested with this library](https://github.com/andrey-ushakov/esc_pos_printer/blob/master/printers.md). 

May I ask you to add your printer model into the table?
It will help me to maintain the library and others to choose the right printer!
Thank you!

**Comment by wesleyxiao** [comment]
> Hi @raindy29,
> 
> Does the library work well for you?
> I've created a [list of printers tested with this library](https://github.com/andrey-ushakov/esc_pos_printer/blob/master/printers.md).
> 
> May I ask you to add your printer model into the table?
> It will help me to maintain the library and others to choose the right printer!
> Thank you!

Hello andrey, i try ticket.printlnMixedKanji('你好'); 
but been mention method is not defined, did i forget something?

**Comment by wesleyxiao** [comment]
Ok, Now it work, i was missing containsChinese: true,
  ticket.text(
    '这是非常好的效果 Hello World',
    containsChinese: true,
  );

also i want to point out when first i paste the code below
  ticket.text(
    'hello ! 中文字 # world @ éphémère &',
    styles: PosStyles(codeTable: PosCodeTable.westEur),
    containsChinese: true,
  );

My editor was show PosCodeTable is undefined, so i delete styles line.
