### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by irperera** [andrey-ushakov/esc_pos_printer#21]
how can i get this to work with a bluetooth thermal printer?

**Comment by andrey-ushakov** [comment]
Hi, it doesn't support Bluetooth printers so far

**Comment by andrey-ushakov** [comment]
Hi @irperera,
The package now supports Bluetooth printers in beta mode.

**Comment by andrey-ushakov** [comment]
Hi @irperera ,

Does the library work well for you?
I've created a [list of printers tested with this library](https://github.com/andrey-ushakov/esc_pos_printer/blob/master/printers.md). 

May I ask you to add your printer model into the table?
It will help me to maintain the library and others to choose the right printer!
Thank you!
