### ISSUE TITLE
Connecting to printer through ethernet.

### ISSUE THREAD

**Issue by ndmunoz10** [andrey-ushakov/esc_pos_printer#22]
I have a printer that connects to a router through an ethernet cable and my device connects through WIFI to this router.
If a ping in the command prompt the ip and port of the printer it responds back and when I'm using the library the library can connect successfully. But it does nothing when I write the printing lines of code. I'm using the same example from the repository I only copy pasted into a new flutter project.

This is the flutter doctor response:

[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at C:\flutter
    • Framework revision 27321ebbad (7 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\MUY Android\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] VS Code (version 1.39.2)
    • VS Code at C:\Users\MUY Android\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Lenovo TB X104F           • HA109XF6      • android-arm • Android 8.1.0 (API 27)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.

Any help would be appreciated.

**Comment by amirulasrof** [comment]
I also having the same issue. Previously it works fine.

**Comment by andrey-ushakov** [comment]
Hi,

Does the issue persist?
Are you able to print over WiFi using another/test app (for example, POS-Printer for iOS)?

**Comment by andrey-ushakov** [comment]
Feel free to reopen if the issue persists.
