### ISSUE TITLE
My Printer when use println just print one paper per println

### ISSUE THREAD

**Issue by HoangHuy98** [andrey-ushakov/esc_pos_printer#25]
Hi theres, i used your library but i get a problem. I used printer canon to test print first. But when i used it print one paper per println. Am I wrong in any settings ? 

 testPrint(String printerIp, BuildContext ctx) {

    Printer.connect(printerIp,
            port: int.parse(portController.text), timeout: Duration(seconds: 5))
        .then((printer) async {
      printer.println(
          'Print text example 1 Print text example 2 Print text example 3 Print text example 4 Print text example 5 Print text example 6 Print text example 7');
      printer.println('Example', styles: PosStyles(bold: true));

      printer.cut();
      printer.disconnect();

    });
  }

**Comment by andrey-ushakov** [comment]
Hi,
Does the issue persist? Could you please show on a photo what's the exact result you are getting? Thank you

**Comment by HoangHuy98** [comment]
Hi, i found what bug i got. I use with the printer print A4 paper, not handheld or POS printer so they print one paper per line. Sorry for this dummy question :p
