### ISSUE TITLE
Unicode doesn't support

### ISSUE THREAD

**Issue by ul-rotha** [andrey-ushakov/esc_pos_printer#26]
Printer.connect('192.168.1.87', port: 9100).then((printer) {
    printer.println(
        'Regular:Welcome Cambodia');
    printer.println('Special 1: ខ្ញុំស្រលាញ់កម្ពុជា ',
        styles: PosStyles(codeTable: PosCodeTable.pc850));
    printer.println('Special 2: blåbærgrød',
        styles: PosStyles(codeTable: PosCodeTable.westEur));

**Comment by andrey-ushakov** [comment]
Hi,

Depending on your printer, it should be possible to print texts in supported languages, here are some examples:
https://github.com/andrey-ushakov/esc_pos_printer#using-code-tables

Unfortunately, my printed doesn't support Khmer language but probably yours does. Try it and I hope it will work!

Feel free to reopen the issue if you have any further questions

**Comment by ul-rotha** [comment]
sorry sir. i could not find code tables for khmer language.

**Comment by amibappy** [comment]
@ul-rotha 

Did you find any solution?
I am having the same problem with Japanese characters.
Please share if you have found any solution.

**Comment by ul-rotha** [comment]
I'm not yet. But I read documentation they said the problem is our printer.

**Comment by amibappy** [comment]
@ul-rotha 

Thanks for your reply.
I am still trying to make this work.

Can I ask you one more thing?

When I try to write like this: 
`styles: PosStyles(codeTable: PosCodeTable.pc850));`

it shows that PosCodeTable is undefined.

Where did you get that? / How did you use that?

**Comment by ul-rotha** [comment]
Some people in Google they suggest us to convert data to PDF or Picture.
And then send it to printer. Cause PDF and picture supportinng unicode.

**Comment by amibappy** [comment]
@ul-rotha 

Yes, I am trying to do the same. If I can make a PDF, then convert the pdf to image and then print the image, I can support every language.

But now the problem is that when I am creating a pdf file, it has lots of extra spaces at the bottom of the page.

Sadly i don't know what to do :(

**Comment by ul-rotha** [comment]
You should use sever generate PDF like crystal report & Ms report viewer .

**Comment by amibappy** [comment]
@ul-rotha 

Thanks for the suggestions. I will definitely look into those.
Anyway, let me know if you find any other easy solution.

**Comment by ul-rotha** [comment]
Yes you too. If find any solution pls let me know. Thanks

**Comment by amibappy** [comment]
@ul-rotha 

Yes of course,

Can I ask you one more thing?

I am absolutely new in Flutter.
Do you know any package that can convert HTML Directly to Image?
I don't want to use PDF to Image.
Thank you.

**Comment by ul-rotha** [comment]
> @ul-rotha
> 
> Yes of course,
> 
> Can I ask you one more thing?
> 
> I am absolutely new in Flutter.
> Do you know any package that can convert HTML Directly to Image?
> I don't want to use PDF to Image.
> Thank you.

Did you find solution?

**Comment by Kimmeng-S** [comment]
Hi I see this ticket was closed. Anyways I also facing this problem. Can you help advice
