### ISSUE TITLE
Barcode alignment

### ISSUE THREAD

**Issue by amirulasrof** [andrey-ushakov/esc_pos_printer#27]
Is it possible to align barcode to center ?

**Comment by andrey-ushakov** [comment]
I've just added this feature :)

Now images and barcodes are centered by default, but you can also pass the `align` parameter for left/right alignment.

BTW, the `PosTextAlign` enum renamed to `PosAlign`. You have to rename it in your code if you are using it somewhere.

I hope it helps!

I'm going to close this issue, but feel free to reopen it if you have any further questions or ideas!
