### ISSUE TITLE
Please add bluetooth support for android

### ISSUE THREAD

**Issue by pjjy** [andrey-ushakov/esc_pos_printer#28]
Many people are using android phones to print receipt.

**Comment by glennmichaelmejias** [comment]
imba pids

**Comment by andrey-ushakov** [comment]
Hi,
I've just added Android support :)
Feel free to re-open this issue if need.

**Comment by andrey-ushakov** [comment]
Hi @pjjy, hi @glennmichaelmejias 

Does the library work well for you?
I've created a [list of printers tested with this library](https://github.com/andrey-ushakov/esc_pos_printer/blob/master/printers.md). 

May I ask you to add your printer model into the table?
It will help me to maintain the library and others to choose the right printer!
Thank you!
