### ISSUE TITLE
 rxdart error

### ISSUE THREAD

**Issue by UnluckyY1** [andrey-ushakov/esc_pos_printer#30]
Because esc_pos_printer >=2.0.0 depends on rxdart >=0.23.0-dev.1 which requires SDK version >=2.6.0 <3.0.0, esc_pos_printer >=2.0.0 is forbidden.

So, because siyou depends on esc_pos_printer ^2.0.0, version solving failed.

**Comment by gvNN7** [comment]
Try upgrade your SDK and rxdart.. in the rxdart package [page](https://pub.dev/packages/rxdart) they put a topic about this upgrade.. 

![image](https://user-images.githubusercontent.com/22239703/74251302-b3b04580-4cca-11ea-9720-f231f7adbdf0.png)

Follow the instructions on the [rxdart utility](https://pub.dev/packages/rxdart_codemod) and all will be fine, these steps worked for me.

**Comment by andrey-ushakov** [comment]
Feel free to reopen if the issue persists.
