### ISSUE TITLE
Barcode Code128

### ISSUE THREAD

**Issue by jcleonis** [andrey-ushakov/esc_pos_printer#32]
Is possible print barcode code128?

**Comment by Thetyne** [comment]
yes, it's possible if your printer support this barcode format.

i tested sucessfully on  TP50 Oxhoo printer.

```
  /// CODE128
  static const code128 = BarcodeType._internal(73);

/// CODE128
  ///
  /// k >= 2
  /// d: '{A'/'{B'/'{C' => '0'–'9', A–D, a–d, $, +, −, ., /, :
  Barcode.code128(List<dynamic> barcodeData) {
    final k = barcodeData.length;
    if (k < 2) {
      throw Exception('Barcode: Wrong data range');
    }

    final regex = RegExp(r'^\{[A-C][\x00-\x7F]+$');
    final bool isDataValid = barcodeData.every((dynamic d) => regex.hasMatch(d.toString()));
    if (!isDataValid) {
      throw Exception('Barcode: Data is not valid');
    }

    _type = BarcodeType.code128;
    _data = _convertData(barcodeData);
  }
```
and i change barcode  method:

```
rawBytes(header + barcode.data + [0]);
```
by

```
if(barcode.type.value <= 6){
      rawBytes(header + barcode.data + [0]);
    }
    else{      
      rawBytes(header + [barcode.data.length] + barcode.data);
    }
```

usage:
{A = QRCode type A
{B = QRCode type B
{C = QRCode type C

final List<String> barcodeData = "{A978020137962".split("");
Barcode barCode = Barcode.code128(barcodeData);
ticket.barcode(barCode);

**Comment by andrey-ushakov** [comment]
@Thetyne thank you!

Can I add your code to the next release, please? Later I will create a `Contributors` section in README.md and add your GitHub nickname / link.

BTW, I think this line 
`final bool isDataValid = barcodeData.every((dynamic d) => regex.hasMatch(d.toString()));`

should be changed by
`final bool isDataValid = regex.hasMatch(barcodeData.join());`

**Comment by Thetyne** [comment]
@andrey-ushakov yes you can add it!

**Comment by Thetyne** [comment]
@andrey-ushakov i can give you the code for print qr code in few days

**Comment by andrey-ushakov** [comment]
That would be awesome!

**Comment by andrey-ushakov** [comment]
CODE128 added to the latest release.
