### ISSUE TITLE
Printing prefixed by '00' on non reverse styling and '01' prefix on reversed styling

### ISSUE THREAD

**Issue by FrankSantoso** [andrey-ushakov/esc_pos_printer#34]
Related to #17 

The exact same issue, but i can't find your proposed solution (delete some lines in your library). 

I am lsing Epson TM-U220B by the way.

Great job so far, appreciate any feedback @andrey-ushakov.

**Comment by andrey-ushakov** [comment]
Hi,
Probably your printer doesn't implement one of the features. I suspect the reverse styling command.
In the Ticket class (ticket.dart), try to remove / comment out line 78:
`bytes += styles.reverse ? cReverseOn.codeUnits : cReverseOff.codeUnits;`

Does it resolve the issue?

**Comment by FrankSantoso** [comment]
Hey thanks for the quick response,

I'm afraid the issue still persists, but instead of showing 00, it now only shows single padded zero (0).

![photo6147755156465363488](https://user-images.githubusercontent.com/35299249/72976572-c0780280-3dca-11ea-8337-220828e0ed29.jpg)

Any other idea i can probably investigate?

**Comment by andrey-ushakov** [comment]
Hi,

I've used Xprinter as a WiFi printer and a cheap noname bluetooth printer.

It seems that your printer only supports a subset of POS/ESC commands. I would print a test ticket using the code from `example.dart` or just try to print using all the text styles (underlined, bold, text align etc) to find which commands/styles are not supported. You can your ticket with the one from `README.me`.

After that, you can remove/comment out them just like you did for `cReverseOn/cReverseOff `command.

**Comment by FrankSantoso** [comment]
Yes, it's a shame my printer only supports a minuscule subset of ESC/POS. 
 
At this point, i'm trying to use method channel from the epson sdk page. I'll figure it out and if i succeed, i'll get back to you, in the mean time i'll close this issue. 

Thanks for the help, cheers!

**Comment by andrey-ushakov** [comment]
Hi @FrankSantoso 
 
I've recently updated the library. It may fix your issue.
May I ask you to print a few test tickets using your printers to check if it helps, please?
