### ISSUE TITLE
Can't print cyrillic text

### ISSUE THREAD

**Issue by Dimolll** [andrey-ushakov/esc_pos_printer#35]
Hi! I can't print cyrilic symbols
it's code 
`final Ticket ticket = Ticket(PaperSize.mm80);
ticket.text('ЙЦУКЕНГШЩЗХЪХЭЖДЛОРПАВЫФЯЧСМИТЬБЮ.',
styles: PosStyles(
          codeTable: PosCodeTable.pc866,
          fontType: PosFontType.fontA,
        ));
    ticket.cut();
    return ticket;`
it's exception
`E/flutter ( 8146): #6      _MyHomePageState.build.<anonymous closure>.<anonymous closure> 
package:blue/main.dart:148
E/flutter ( 8146): #7      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:706
E/flutter ( 8146): #8      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:789
E/flutter ( 8146): #9      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:182
E/flutter ( 8146): #10     TapGestureRecognizer.handleTapUp 
package:flutter/…/gestures/tap.dart:486
E/flutter ( 8146): #11     BaseTapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:264
E/flutter ( 8146): #12     BaseTapGestureRecognizer.acceptGesture 
package:flutter/…/gestures/tap.dart:236
E/flutter ( 8146): #13     GestureArenaManager.sweep 
package:flutter/…/gestures/arena.dart:156
E/flutter ( 8146): #14     GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:222
E/flutter ( 8146): #15     GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:198
E/flutter ( 8146): #16     GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:156
E/flutter ( 8146): #17     GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:102
E/flutter ( 8146): #18     GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:86
E/flutter ( 8146): #19     _rootRunUnary  (dart:async/zone.dart:1138:13)
E/flutter ( 8146): #20     _CustomZone.runUnary  (dart:async/zone.dart:1031:19)
E/flutter ( 8146): #21     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:933:7)
E/flutter ( 8146): #22     _invoke1  (dart:ui/hooks.dart:273:10)
E/flutter ( 8146): #23     _dispatchPointerDataPacket  (dart:ui/hooks.dart:182:5)`
Can you help me with this?

**Comment by andrey-ushakov** [comment]
Hi,
It should be possible to print Cyrillic symbols, here are some examples (including printing Cyrillic):
https://github.com/andrey-ushakov/esc_pos_printer#using-code-tables

Feel free to reopen the issue if you have any further questions
