### ISSUE TITLE
Printing Reverse Text Always

### ISSUE THREAD

**Issue by renenucci** [andrey-ushakov/esc_pos_printer#37]
Hi,

After I update plugin to latest version, I faced this issue, even the example app results in the same, **all text are printed as reverse text (black background and "white" font)**, tried in two diferent printers, and one of them, beyond that, the printer shutdown in middle of printing. (Maybe an issue with temperature, idk).

Any one face this issue?

**Comment by michalsuryntequiqo** [comment]
Yeah, the same for me. 
I’m using the newest version of the plugin, 2.1.2
![C974CD0B-F8A9-4AFD-8D4A-455911D9933C](https://user-images.githubusercontent.com/46317368/73985134-b0b7fc80-493a-11ea-9a2d-c700048f1a2c.jpeg)

**Comment by andrey-ushakov** [comment]
Humm interesting...

Could you please try to print something very simple:
```dart
final Ticket ticket = Ticket(PaperSize.mm80);
ticket.text('Hello world!');
ticket.feed(2);
ticket.cut();
```
Does it happen every time?

**Comment by renenucci** [comment]
> Humm interesting...
> 
> Could you please try to print something very simple:
> 
> ```dart
> final Ticket ticket = Ticket(PaperSize.mm80);
> ticket.text('Hello world!');
> ticket.feed(2);
> ticket.cut();
> ```
> 
> Does it happen every time?

Yeah, happens every time in all text, the shutdown moment still random.

I'll try with ticket.feed(2) line and tell if something change...

**Comment by andrey-ushakov** [comment]
Hi @renenucci,
Hi @michalsuryntequiqo,

What are your printer models, please?
Have you tested with a previous version of the library (before the `Ticket` class was created)?

**Comment by michalsuryntequiqo** [comment]
Before, the app was still using plugin version 1.0.0 and the printed text was fine (no background, just black text). After upgrading and refactoring code to use `Ticket` class, printer prints black backgrounds.

**Comment by renenucci** [comment]
> Hi @renenucci,
> Hi @michalsuryntequiqo,
> 
> What are your printer models, please?
> Have you tested with a previous version of the library (before the `Ticket` class was created)?

Knup kp 1022 printer 80mm
![WhatsApp Image 2020-02-10 at 22 13 40](https://user-images.githubusercontent.com/18505538/74204673-ec143d00-4c52-11ea-9923-17b5826c4cd0.jpeg)


Look at the test with your code (Hello World)

![WhatsApp Image 2020-02-10 at 22 13 49](https://user-images.githubusercontent.com/18505538/74204669-e61e5c00-4c52-11ea-903e-1e4deb50d86d.jpeg)

Version of pub package
esc_pos_printer: ^2.1.2

**Comment by renenucci** [comment]
I commented the line:

> 78:     bytes += styles.reverse ? cReverseOn.codeUnits : cReverseOff.codeUnits;

And got this result: 
![WhatsApp Image 2020-02-10 at 23 11 44](https://user-images.githubusercontent.com/18505538/74206638-fcc8b100-4c5a-11ea-81e7-ac038a505039.jpeg)

Is almost fine, except by special sections (1 and 2), and underscore in all except regular.

**Comment by andrey-ushakov** [comment]
Hi @renenucci, @michalsuryntequiqo 

I've recently updated the library. It may fix the underline / reverse issues.

May I ask you to print a few test tickets using your printers to check if it helps, please?

**Comment by andrey-ushakov** [comment]
BTW, the Bluetooth printing moved to [this package](https://github.com/andrey-ushakov/esc_pos_bluetooth).

Feel free to create a new ticket in that repo if the issue persists.
