### ISSUE TITLE
Greek characters problem

### ISSUE THREAD

**Issue by movieator** [andrey-ushakov/esc_pos_printer#4]
Hi, i'm trying to print greek characters, using the "PosCodeTable.greek" option but i'm getting the following error:

E/flutter (19694): [ERROR:flutter/lib/ui/ui_dart_state.cc(154)] Unhandled Exception: Invalid argument (string): Contains invalid characters.: "αβγδώ"
E/flutter (19694): #0      _UnicodeSubsetEncoder.convert (dart:convert/ascii.dart:86:9)
E/flutter (19694): #1      Latin1Codec.encode (dart:convert/latin1.dart:40:46)
E/flutter (19694): #2      Printer._print (package:esc_pos_printer/src/printer.dart:109:26)
E/flutter (19694): #3      Printer.println (package:esc_pos_printer/src/printer.dart:130:5)
E/flutter (19694): #4      _MyHomePageState._print.<anonymous closure> (package:print_app/main.dart:33:15)
E/flutter (19694): #5      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (19694): #6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (19694): #7      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
E/flutter (19694): #8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
E/flutter (19694): #9      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
E/flutter (19694): #10     Future._completeWithValue (dart:async/future_impl.dart:483:5)
E/flutter (19694): #11     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
E/flutter (19694): #12     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (19694): #13     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (19694): #14     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (19694): #15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (19694): #16     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (19694): #17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

My print code is:
`printer.println('αβγδώ',
          styles: PosStyles(codeTable: PosCodeTable.greek));`

**Comment by andrey-ushakov** [comment]
Hi there,

Yeah, that's because standard dart's latin1 codec is currently used to convert strings from unicode to appropriate code table.

So to resolve this problem, a new codec unicode <--> greek code table should be written.

Unfortunately, I can't really write and test it because it seems that my pos printer doesn't really support all the greek characters (at least, there is no lowercase characters) :

![Greek](https://hostpic.xyz/files/15629241533601288532.jpg)

So it will be hard to test the codec...

**Comment by andrey-ushakov** [comment]
Hi,
It should be possible to print Greek texts, here are some examples (including printing in Greek):
https://github.com/andrey-ushakov/esc_pos_printer#using-code-tables

Feel free to reopen the issue if you have any further questions
