### ISSUE TITLE
Printer not listing in bluetooth scanning

### ISSUE THREAD

**Issue by emsyneapps** [andrey-ushakov/esc_pos_printer#41]
Tried with evolute prime ESC Bluetooth thermal printer. My printer not listing in scanned Bluetooth device list. 

Is this package support above mentioned printer ? Please provide some supporting printer list.

**Comment by andrey-ushakov** [comment]
Hi @emsyneapps,

It's hard to say why it's happening...
Have you tried to use this printer with an app such as [POS-Printer](https://apps.apple.com/fr/app/pos-printerv1-0/id1133503452)?

BTW, I've created a page to list supporting printers [here](https://github.com/andrey-ushakov/esc_pos_printer/blob/master/printers.md). It was created yesterday, so you will find only few models here.

Could you please provide your exact printer model and perhaps a link or some photos? Probably I could find this model to test.

Thank you

**Comment by emsyneapps** [comment]
> 
> 
> Hi @emsyneapps,
> 
> It's hard to say why it's happening...
> Have you tried to use this printer with an app such as [POS-Printer](https://apps.apple.com/fr/app/pos-printerv1-0/id1133503452)?
> 
> BTW, I've created a page to list supporting printers [here](https://github.com/andrey-ushakov/esc_pos_printer/blob/master/printers.md). It was created yesterday, so you will find only few models here.
> 
> Could you please provide your exact printer model and perhaps a link or some photos? Probably I could find this model to test.
> 
> Thank you

Evolute, Model No: PRIDE

https://www.justransact.com/brochure/evolute-pride-mobile-printer-brochure.pdf

**Comment by andrey-ushakov** [comment]
Thank you. Unfortunately, I can't find this model on Amazon in Europe, it seems it's only available in India. Therefore I can't really test it... But have you tried the app above? Does it work?

**Comment by emsyneapps** [comment]
Yes, I have tried the above app, it also shows the same response. Not listing my printer device.

**Comment by andrey-ushakov** [comment]
So if you can’t find your printer with another app as well, I think the easiest solution would be using another Bluetooth printer.

Im going to close this issue, feel free to reopen it if you have further questions.

**Comment by andrey-ushakov** [comment]
Btw I didn’t find in the specification that’s a pos esc printer, are you sure about it ?
