### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method startScan on channel flutter_bluetooth_basic/methods)

### ISSUE THREAD

**Issue by billyurs** [andrey-ushakov/esc_pos_printer#42]
Please help me to setup bluetooth connection

**Comment by andrey-ushakov** [comment]
Hi,

The Bluetooth printing library has been updated and moved to [esc_pos_bluetooth](https://github.com/andrey-ushakov/esc_pos_bluetooth) package.

Feel free to create a new ticket in that repo if the issue persists.
