### ISSUE TITLE
Bluetooth Printers not list.

### ISSUE THREAD

**Issue by elbrusnt** [andrey-ushakov/esc_pos_printer#43]
printerManager.scanResults.listen((devices) async {
      print(devices);
      setState(() {
        _devices = devices;
      });
    });

####  When pressed start scan button    I  get  this  in console

D/ViewRootImpl@4ead107[MainActivity](19001): ViewPostIme pointer 0
D/ViewRootImpl@4ead107[MainActivity](19001): ViewPostIme pointer 1
I/flutter (19001): []
D/BluetoothBasicPlugin(19001): start scan 
I/flutter (19001): []
D/BluetoothAdapter(19001): STATE_ON
I/flutter (19001): []
D/BluetoothAdapter(19001): STATE_ON
D/BluetoothAdapter(19001): STATE_ON
D/BluetoothAdapter(19001): BLE support array set: 010011
D/BluetoothLeScanner(19001): Start Scan with callback
D/BluetoothLeScanner(19001): onScannerRegistered() - status=0 scannerId=7 mScannerId=0
D/BluetoothAdapter(19001): STATE_ON
D/BluetoothAdapter(19001): STATE_ON
D/BluetoothLeScanner(19001): Stop Scan with callback

####  But  printer  can not scanned
Could you help ?

**Comment by andrey-ushakov** [comment]
Hi,

Could you please provide the printer manufacturer and model?
If you have a url with a specification it would be even better.
Thank you!

**Comment by andrey-ushakov** [comment]
Hi,

The Bluetooth printing library has been updated and moved to [esc_pos_bluetooth](https://github.com/andrey-ushakov/esc_pos_bluetooth) package.

Feel free to create a new ticket (with your printer model please) in that repo if the issue persists.

**Comment by AirborneEagle** [comment]
@andrey-ushakov 
Can we re-open this?

My printer is:
Star Micronics TSP650

my pubspec:
```
  esc_pos_printer: ^3.1.6
  esc_pos_bluetooth: ^0.2.8
  esc_pos_utils: ^0.3.6
```

I cannot get it to show on the list at all. 
My headphones show up though :P
