### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by niktses** [andrey-ushakov/esc_pos_printer#46]
in my case it doesn't seem to pass this point:

checks for state 1 or 0 here: 

_bluetoothManager.state.listen((state) async {
      switch (state) {
        case BluetoothManager.CONNECTED:
          // To avoid double call
          if (!_isConnected) {
            await _bluetoothManager.writeData(bytes);
            completer.complete(PosPrintResult.success);
          }
          // TODO sending disconnect signal should be event-based
          _runDelayed(3).then((dynamic v) async {
            await _bluetoothManager.disconnect();
            _isPrinting = false;
          });
          _isConnected = true;
          break;
        case BluetoothManager.DISCONNECTED:
          _isConnected = false;
          break;
        default:
          break;
      }
    });

but the actual state is 10 - 13 here:

  private void state(Result result){
    try {
      switch(mBluetoothAdapter.getState()) {
        case BluetoothAdapter.STATE_OFF:
          result.success(BluetoothAdapter.STATE_OFF); <------ 10
          break;
        case BluetoothAdapter.STATE_ON: <------- 12
          result.success(BluetoothAdapter.STATE_ON);
          break;
        case BluetoothAdapter.STATE_TURNING_OFF: <---- 13
          result.success(BluetoothAdapter.STATE_TURNING_OFF);
          break;
        case BluetoothAdapter.STATE_TURNING_ON:  <----- 11
          result.success(BluetoothAdapter.STATE_TURNING_ON);
          break;
        default:
          result.success(0);
          break;
      }
    } catch (SecurityException e) {
      result.error("invalid_argument", "Argument 'address' not found", null);
    }
  }

this doesn't seem specific to my printer

**Comment by andrey-ushakov** [comment]
Hi,

The Bluetooth printing library has been updated and moved to [this package](https://github.com/andrey-ushakov/esc_pos_bluetooth).

Feel free to create a new ticket in that repo if the issue persists.
