### ISSUE TITLE
Is it possible to align image ?

### ISSUE THREAD

**Issue by kakzaki** [andrey-ushakov/esc_pos_printer#47]
thanks for your hardwork, Is it possible to align image ?

**Comment by andrey-ushakov** [comment]
Hi there,

Thank you for your interest! I've just added this feature :)

Now images and barcodes are centered by default, but you can also pass the `align` parameter for left/right alignment.

BTW, the `PosTextAlign` enum renamed to `PosAlign`. You have to rename it in your code if you are using it somewhere.

I hope it helps!

I'm going to close this issue, but feel free to reopen it if you have any further questions or ideas!
