### ISSUE TITLE
Can you please help with likely ESC/POS (usually thermal) network printers?

### ISSUE THREAD

**Issue by chrisgate** [andrey-ushakov/esc_pos_printer#5]
Can you please help with likely ESC/POS (usually thermal) network printers?

I am kind of confused searching to buy any workable printer for test.

Thanks in anticipation.

Cheers

**Comment by andrey-ushakov** [comment]
Hi,
I'm using a POS/ESC 80mm WiFi printer from Xprinter. It costs around $40-$50.
I've tested it to print in English and French (with special characters) and it's works well so far.
It seems that for some other languages such as Greek it's maybe not a good choice.

Hope it helps!

**Comment by chrisgate** [comment]
It really help but i am here in Nigeria Africa and i must get what i am buying in specific bcoz of cost of return and all that.
I have actually seen many of  POS/ESC 80mm WiFi printer (Xprinter brand) but please, can u share the Model of the Printer in question. Buying online can be very frustrated .

Thanks in anticipations.

Chris

**Comment by andrey-ushakov** [comment]
Hi Chris,

Sure, the exact model is Xprinter XP-N160I.

Hope it helps !
