### ISSUE TITLE
After print show error "Unknow Error: -2"

### ISSUE THREAD

**Issue by luissouza** [andrey-ushakov/esc_pos_printer#53]
After print page show error **"Unknow Error: -2"**

Error Log: 

`D/BluetoothBasicPlugin(31951): start scan
D/BluetoothAdapter(31951): STATE_ON
D/BluetoothLeScanner(31951): onClientRegistered() - status=0 clientIf=5 mClientIf=0
D/BluetoothAdapter(31951): STATE_ON
I/flutter (31951): UI: Devices found Instance of 'Future<int>'
D/BluetoothAdapter(31951): STATE_ON
D/BluetoothLeScanner(31951): could not find callback wrapper
D/BluetoothSocket(31951): try to open PaxInternalPrinter
D/BluetoothSocket(31951): =====[tangkw]:to connect BT_Printer...
W/BluetoothAdapter(31951): getBluetoothService() called with no BluetoothManagerCallback
D/BThermalPrinterPlugin(31951): android.bluetooth.device.action.ACL_CONNECTED
D/BluetoothBasicPlugin(31951): stateStreamHandler, current action: android.bluetooth.device.action.ACL_CONNECTED
E/DeviceConnFactoryManager(31951): wait read
D/BluetoothSocket(31951): write PaxInternalPrinter:@a0E0V0B0-0M0!�$��.Regular: aA bB cC dD eE fF gG hH iI jJ kK lL mM nN oO pP qQ rR sS tT uU vV wW xX yY zZ
D/BluetoothSocket(31951): @a0E0V0B0-0M0!�$��.tSpecial 1: 嗬 枞 樯   缜 粼
D/BluetoothSocket(31951): @a0E0V0B0-0M0!�$��.tSpecial 2: bl錬鎟gr鴇
D/BluetoothSocket(31951): @a0E1V0B0-0M0!�$��.Bold text
D/BluetoothSocket(31951): @a0E0V0B1-0M0!�$��.Reverse text
D/BluetoothSocket(31951): @a0E0V0B0-1M0!�$��.Underlined text
D/BluetoothSocket(31951):
D/BluetoothSocket(31951): @a0E0V0B0-0M0!�$��.Align left
D/BluetoothSocket(31951): @a1E0V0B0-0M0!�$��.Align center
D/BluetoothSocket(31951): @a2E0V0B0-0M0!�$��.Align right
D/BluetoothSocket(31951):
D/BluetoothSocket(31951): @a0E0V0B0-0M0!$��.Text size 200%
D/BluetoothSocket(31951): @
D/BluetoothSocket(31951): write PaxInternalPrinter:
D/BluetoothSocket(31951): write PaxInternalPrinter:h
W/System.err(31951): java.io.IOException: bt socket closed, read return: -1
W/System.err(31951): 	at android.bluetooth.BluetoothSocket.read(BluetoothSocket.java:630)
W/System.err(31951): 	at android.bluetooth.BluetoothInputStream.read(BluetoothInputStream.java:96)
W/System.err(31951): 	at java.io.InputStream.read(InputStream.java:101)
W/System.err(31951): 	at com.gprinter.io.BluetoothPort.readData(BluetoothPort.java:130)
W/System.err(31951): 	at com.tablemi.flutter_bluetooth_basic.DeviceConnFactoryManager.readDataImmediately(DeviceConnFactoryManager.java:418)
W/System.err(31951): 	at com.tablemi.flutter_bluetooth_basic.DeviceConnFactoryManager$PrinterReader.run(DeviceConnFactoryManager.java:498)
E/BluetoothPort(31951): connection device is lost
E/DeviceConnFactoryManager(31951):  read 0
W/BluetoothAdapter(31951): getBluetoothService() called with no BluetoothManagerCallback
D/BThermalPrinterPlugin(31951): android.bluetooth.device.action.ACL_DISCONNECTED
D/BluetoothBasicPlugin(31951): stateStreamHandler, current action: android.bluetooth.device.action.ACL_DISCONNECTED
`

**Comment by andrey-ushakov** [comment]
Hi,

Bluetooth printing moved to [this](https://github.com/andrey-ushakov/esc_pos_bluetooth) package. Could you please upgrade your dependencies and re-test, please?

Feel free to reopen if the issue persists.
