### ISSUE TITLE
Image printing in sample was remove. Why?

### ISSUE THREAD

**Issue by ccfiel** [andrey-ushakov/esc_pos_printer#54]
@andrey-ushakov  I have notice in this line
https://github.com/andrey-ushakov/esc_pos_printer/blob/master/example/example.dart#L63
Image printing is comment out. Why?
Is this package does not support image printing anymore?

**Comment by andrey-ushakov** [comment]
Hi @ccfiel,
No worries, the package does support image printing. The code is commented out to make it executable with pure Dart: `dart example.dart`.
To print an image in the provided example, we have to import `package:flutter/services.dart` which will make the example incompatible with pure Dart.
You can check the full example in the `discover_printers` project:
https://github.com/andrey-ushakov/esc_pos_printer/blob/master/example/discover_printers/lib/main.dart#L135

**Comment by ccfiel** [comment]
@andrey-ushakov Thanks!
