### ISSUE TITLE
Error Print Barcode

### ISSUE THREAD

**Issue by luissouza** [andrey-ushakov/esc_pos_printer#55]
Hello! Im trying to print with **barcode**, in this case **ean13**, and all the tests i have the error: 
Someone know what i can do? I think is a bug..

D/BluetoothBasicPlugin( 1358): start scan
D/BluetoothAdapter( 1358): STATE_ON
D/BluetoothLeScanner( 1358): onClientRegistered() - status=0 clientIf=5 mClientIf=0
D/BluetoothAdapter( 1358): STATE_ON
I/flutter ( 1358): UI: Devices found Instance of 'Future<int>'
D/BluetoothAdapter( 1358): STATE_ON
D/BluetoothLeScanner( 1358): could not find callback wrapper
D/BluetoothSocket( 1358): try to open PaxInternalPrinter
D/BluetoothSocket( 1358): =====[tangkw]:to connect BT_Printer...
W/BluetoothAdapter( 1358): getBluetoothService() called with no BluetoothManagerCallback
D/BThermalPrinterPlugin( 1358): android.bluetooth.device.action.ACL_CONNECTED
D/BluetoothBasicPlugin( 1358): stateStreamHandler, current action: android.bluetooth.device.action.ACL_CONNECTED
E/DeviceConnFactoryManager( 1358): wait read
D/BluetoothSocket( 1358): write PaxInternalPrinter:@a1E1V0B0-1M0!p$��.Demo text
D/BluetoothSocket( 1358): @
D/BluetoothSocket( 1358): E0V0B0-1M0!�$��.Item     E0V0B0-1M0!�$>.Price
D/BluetoothSocket( 1358): @.H.k1234567890423�d
D/BluetoothSocket( 1358):
D/BluetoothSocket( 1358):
D/BluetoothSocket( 1358):
D/BluetoothSocket( 1358):
D/BluetoothSocket( 1358): V0
D/BluetoothSocket( 1358): write PaxInternalPrinter:
W/System.err( 1358): java.io.IOException: bt socket closed, read return: -1
W/System.err( 1358): 	at android.bluetooth.BluetoothSocket.read(BluetoothSocket.java:630)
W/System.err( 1358): 	at android.bluetooth.BluetoothInputStream.read(BluetoothInputStream.java:96)
W/System.err( 1358): 	at java.io.InputStream.read(InputStream.java:101)
W/System.err( 1358): 	at com.gprinter.io.BluetoothPort.readData(BluetoothPort.java:130)
W/System.err( 1358): 	at com.tablemi.flutter_bluetooth_basic.DeviceConnFactoryManager.readDataImmediately(DeviceConnFactoryManager.java:418)
W/System.err( 1358): 	at com.tablemi.flutter_bluetooth_basic.DeviceConnFactoryManager$PrinterReader.run(DeviceConnFactoryManager.java:498)
E/BluetoothPort( 1358): connection device is lost
E/DeviceConnFactoryManager( 1358):  read 0
W/BluetoothAdapter( 1358): getBluetoothService() called with no BluetoothManagerCallback
D/BThermalPrinterPlugin( 1358): android.bluetooth.device.action.ACL_DISCONNECTED
D/BluetoothBasicPlugin( 1358): stateStreamHandler, current action: android.bluetooth.device.action.ACL_DISCONNECTED
E/BluetoothSocket( 1358): java.lang.Throwable
E/BluetoothSocket( 1358): 	at android.bluetooth.BluetoothSocket.write(BluetoothSocket.java:650)
E/BluetoothSocket( 1358): 	at android.bluetooth.BluetoothOutputStream.write(BluetoothOutputStream.java:85)
E/BluetoothSocket( 1358): 	at com.gprinter.io.BluetoothPort.writeDataImmediately(BluetoothPort.java:113)
E/BluetoothSocket( 1358): 	at com.tablemi.flutter_bluetooth_basic.DeviceConnFactoryManager.sendDataImmediately(DeviceConnFactoryManager.java:386)
E/BluetoothSocket( 1358): 	at com.tablemi.flutter_bluetooth_basic.DeviceConnFactoryManager$1$1.run(DeviceConnFactoryManager.java:475)
E/BluetoothSocket( 1358): 	at java.lang.Thread.run(Thread.java:761)
E/BluetoothSocket( 1358): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
E/BluetoothSocket( 1358): 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:278)
E/BluetoothSocket( 1358): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:273)
E/BluetoothSocket( 1358): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/BluetoothSocket( 1358): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/BluetoothSocket( 1358): 	at java.lang.Thread.run(Thread.java:761)
W/System.err( 1358): java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.OutputStream.flush()' on a null object reference
D/DeviceConnFactoryManager( 1358): abnormal disconnection
W/System.err( 1358): 	at com.gprinter.io.BluetoothPort.writeDataImmediately(BluetoothPort.java:114)
W/System.err( 1358): 	at com.tablemi.flutter_bluetooth_basic.DeviceConnFactoryManager.sendDataImmediately(DeviceConnFactoryManager.java:386)
W/System.err( 1358): 	at com.tablemi.flutter_bluetooth_basic.DeviceConnFactoryManager$1$1.run(DeviceConnFactoryManager.java:475)
W/System.err( 1358): 	at java.lang.Thread.run(Thread.java:761)
W/System.err( 1358): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
W/System.err( 1358): 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:278)
W/System.err( 1358): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:273)
W/System.err( 1358): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
W/System.err( 1358): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
W/System.err( 1358): 	at java.lang.Thread.run(Thread.java:761)

**Comment by andrey-ushakov** [comment]
Hi,

Bluetooth printing moved to [this](https://github.com/andrey-ushakov/esc_pos_bluetooth) package. Could you please upgrade your dependencies and re-test, please?

Feel free to reopen if the issue persists.

**Comment by luissouza** [comment]
Andrey,

Thanks for your help, I upgrade the package to **esc_pos_bluetooth: ^0.2.1** but the issue persist. What I can do? All the texts are printing without problems, but when i put barcode my app crash.

**This is the code to print barcode:**

```
final List<int> barData = [1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 4];
 ticket.barcode(Barcode.upcA(barData));
```


**This is the error:**

`Reloaded 53 of 1247 libraries in 2,725ms.
D/BluetoothBasicPlugin( 9801): start scan
D/BluetoothAdapter( 9801): STATE_ON
D/BluetoothLeScanner( 9801): onClientRegistered() - status=0 clientIf=5 mClientIf=0
D/BluetoothAdapter( 9801): STATE_ON
I/flutter ( 9801): UI: Devices found Instance of 'Future<int>'
D/BluetoothAdapter( 9801): STATE_ON
D/BluetoothLeScanner( 9801): could not find callback wrapper
D/BluetoothSocket( 9801): try to open PaxInternalPrinter
D/BluetoothSocket( 9801): =====[tangkw]:to connect BT_Printer...
W/BluetoothAdapter( 9801): getBluetoothService() called with no BluetoothManagerCallback
D/BThermalPrinterPlugin( 9801): android.bluetooth.device.action.ACL_CONNECTED
D/BluetoothBasicPlugin( 9801): stateStreamHandler, current action: android.bluetooth.device.action.ACL_CONNECTED
E/DeviceConnFactoryManager( 9801): wait read
D/BluetoothSocket( 9801): write PaxInternalPrinter:@Ha1k�12345678904�d
D/BluetoothSocket( 9801):
D/BluetoothSocket( 9801):
D/BluetoothSocket( 9801):
D/BluetoothSocket( 9801):
D/BluetoothSocket( 9801): V0
D/BluetoothSocket( 9801): write PaxInternalPrinter:
W/System.err( 9801): java.io.IOException: bt socket closed, read return: -1
W/System.err( 9801): 	at android.bluetooth.BluetoothSocket.read(BluetoothSocket.java:630)
W/System.err( 9801): 	at android.bluetooth.BluetoothInputStream.read(BluetoothInputStream.java:96)
W/System.err( 9801): 	at java.io.InputStream.read(InputStream.java:101)
W/System.err( 9801): 	at com.gprinter.io.BluetoothPort.readData(BluetoothPort.java:130)
W/System.err( 9801): 	at com.tablemi.flutter_bluetooth_basic.DeviceConnFactoryManager.readDataImmediately(DeviceConnFactoryManager.java:418)
W/System.err( 9801): 	at com.tablemi.flutter_bluetooth_basic.DeviceConnFactoryManager$PrinterReader.run(DeviceConnFactoryManager.java:498)
E/BluetoothPort( 9801): connection device is lost
E/DeviceConnFactoryManager( 9801):  read 0
W/BluetoothAdapter( 9801): getBluetoothService() called with no BluetoothManagerCallback
D/BThermalPrinterPlugin( 9801): android.bluetooth.device.action.ACL_DISCONNECTED
D/BluetoothBasicPlugin( 9801): stateStreamHandler, current action: android.bluetooth.device.action.ACL_DISCONNECTED
`
