### ISSUE TITLE
No Star Micronics Printer Compatibility

### ISSUE THREAD

**Issue by AirborneEagle** [andrey-ushakov/esc_pos_printer#57]
it seems that star micronics is a very dominant brand of printers in the POS world, however, when I attempt to print from one, it behaves poorly. It behaves similar to the way that my desktop home printer behaves.

 I get one line per page, with `0B00!.` in front of the value. 
example:
`0B00!.col30B00!.60B00!.col3`
followed by about a foot of empty paper
`0B00!.Text Size 200%`
followed by about a foot more blank paper

I am guessing that there is just some encoding setting to change or something?

**Comment by AirborneEagle** [comment]
Update:
With the recent major version change, I have updated to use the three separate packages.
I have not been able to test on a star printer yet, but I noticed new behavior with my home desktop printer.
it now will only print the first line in the ticket, whereas before it would print every line on its own page

the line would show like:
`00  ͍0B00  ͍!⮑.Text Size 200%`
but now it shows like:
`0⮑.Text Size 200%`

**Comment by andrey-ushakov** [comment]
What're the exact models of your printers, please?
Both of them support ESC/POS commands, right?

**Comment by AirborneEagle** [comment]
Star Micronics SP700 / SP742 Ethernet printer was the one that I tested specifically.

I just found this  link. I will need to check this.
https://www.starmicronics.com/absolutefm/absolutefm/afmviewfaq.aspx?faqid=351

**Comment by andrey-ushakov** [comment]
Ok! 

I'm going to close this issue, but feel free to reopen it if the issue persists!

**Comment by AirborneEagle** [comment]
@andrey-ushakov 
We may or may not want to re-open this issue
Update:
I was able to create a successful print with the star.
However it was only doable when adjusting the dip switches under the printer.
this is a clip from the Star Manual:
https://www.star-m.jp/eng/service/usermanual/sp700-9w_hm_en.pdf
![Screen Shot 2020-03-21 at 4 26 55 PM](https://user-images.githubusercontent.com/13696163/77237819-f817e680-6b90-11ea-9b6d-417b0322a157.png)
So if any of you are wanting to use an SP700 or 742, there is your answer.

For me however, I need to be able to keep the Printer in Star mode, so that it maintains compatibility with the other systems already using it (Square, Clover, and others)

So my question is, would you be interested in having a package here that can translate to Star Command Emulation? 
Or perhaps I should just make it is own pub.dev package , `esc_pos_to_star_micronics` or something?


I did find this doc detailing their command emulation:
https://www.starmicronics.com/support/Mannualfolder/com-emu_starline_cm_en.pdf

so either way, it seems like it should be totally doable.
thoughts?

**Comment by andrey-ushakov** [comment]
I would say that at the moment it should be a separate package. I have no possibility to test Star-branded printers now.

However, very probably one day we will implement printer profiles, just like in this php library:
https://github.com/mike42/escpos-php#using-a-capabilityprofile
Then we can add Star Micronics printers.
