### ISSUE TITLE
printRow - PosColumn alignment issue

### ISSUE THREAD

**Issue by terence-truong** [andrey-ushakov/esc_pos_printer#6]
I am using a BTP-R880NP Network Receipt Printer to print:

`Bag of Cherries......1....3.99....3.99`
`Drink................1...14.95...14.99`

Basically, I'm trying to align each column to their own alignment. (1) align: left, (2) align: center, (3) align: right, (4) align: right. But instead they are all aligning to what i set for the first column. They are all aligning to the left.

My code:

```
                                          printer.printRow([
                                            PosColumn(
                                              text: 'Bag of Cherries', // Drink
                                              width: 6,
                                              styles: PosStyles(
                                                align: PosTextAlign.left,
                                              ),
                                            ),
                                            PosColumn(
                                              text: '1', // 1
                                              width: 1,
                                              styles: PosStyles(
                                                align: PosTextAlign.center,
                                              ),
                                            ),
                                            PosColumn(
                                              text:
                                                  '3.99', // 14.95
                                              width: 2,
                                              styles: PosStyles(
                                                align: PosTextAlign.right,
                                              ),
                                            ),
                                            PosColumn(
                                              text:
                                                  '3.99', //14.95
                                              width: 3,
                                              styles: PosStyles(
                                                align: PosTextAlign.right,
                                              ),
                                            ),
                                          ]);
```

**Comment by andrey-ushakov** [comment]
Hi,

Thank you for submitting this!
It seems that it's impossible to use standard printer's commands to justify content in different columns on the same line (source: https://github.com/qzind/tray/issues/212)

So I've added some math to calculate text position in columns.

Could you please test if now it works as expected?

**Comment by terence-truong** [comment]
Hi Andrey,

Thank you for looking into this. I pulled your changes, and it looks really good.

I tried it, but now it's wrapping to the next line. It looks like it's 3 or 4 characters that gets put onto the next line for me. I've been adjusting the column width differently to see if that helps, but it doesn't.

Here are my relevant printer specs:

> Resolution: 203X180DPI
Print Width(max): 80mm
Fixed LeftMargin: 7mm
Fixed RightMargin: 9mm
Curent CodePage: PC437

Thanks again.

-Terence

**Comment by andrey-ushakov** [comment]
Hi Terence,

Normally you should be able to print 48 characters per line, could you please check that?

Are you trying to print the same data you shared above?

Thanks

**Comment by terence-truong** [comment]
Hi Andrey,

I'm only able to print 42 characters per line. Also, I am printing the same data I shared above.

I looked up the specs on my printer:

> Resolution: 203 DPI x 180DPI

>Characters Per Line – 
Font A: 42 (80mm) / 37 (58mm)
Font B: 56 (80mm) / 49 (58mm)

>Characters Size – 
Font A: 12 x 24
Font B: 9 x 17

**Comment by gvNN7** [comment]
I'm facing the same issue using the Epson TM T88V-i (via network), if any alignment is used in 
PosColumn, like bellow, the width of column is ignored or are wrapped to the next line, i have removed the align option and the alignment is being provided by width, but i think that is not a good deal.. 

> Characters per line (default)
80mm -> Font A: 42; Font B: 56 
58mm -> Font A: 30; Font B: 40

OBS: there is no margin applied to the printer
 
![image](https://user-images.githubusercontent.com/22239703/73940706-afe78200-48ca-11ea-80f6-914b4b5cb4fc.png) 
(I have another column above this code to complement the 12 columns)

![image](https://user-images.githubusercontent.com/22239703/73941033-47e56b80-48cb-11ea-9acf-81a07716bd0e.png)

**Comment by andrey-ushakov** [comment]
The issue should be fixed in the latest releases. Don't hesitate to reopen the ticket if the problem persists.
