### ISSUE TITLE
how to you have tested MUNBYN MU-ITPP047USEW-BK WiFi/Ethernet??

### ISSUE THREAD

**Issue by sante85** [andrey-ushakov/esc_pos_printer#69]
how to you have tested MUNBYN MU-ITPP047USEW-BK WiFi/Ethernet??

_Originally posted by @sante85 in https://github.com/andrey-ushakov/esc_pos_printer/issues/67#issuecomment-617247568_

**Comment by sante85** [comment]
@andrey-ushakov i upload a video
that use you example code

**Comment by andrey-ushakov** [comment]
duplicate https://github.com/andrey-ushakov/esc_pos_printer/issues/67

If it's printing black tickets using this lib and another app as well as you said, there is not too much we could do for you. Try to check if the paper inserted correctly or probably it's a hardware problem. Please keep the communication in one thread only (https://github.com/andrey-ushakov/esc_pos_printer/issues/67).

**Comment by sante85** [comment]
hardware problem: no,
paper is correct
I use you example application: 
https://github.com/andrey-ushakov/esc_pos_printer/tree/master/example.

If you want, you could be help me.

there aren't any others libraries.

**Comment by sante85** [comment]
can post a simple code that run right on MUNBYN printer?

Best Regards
