### ISSUE TITLE
Can't print special characters.

### ISSUE THREAD

**Issue by larssn** [andrey-ushakov/esc_pos_printer#7]
So I've tried printing the example from the latin1 codec (since this plugin is already using it), which is: 'blåbærgrød'.

So: `printer.println('blåbærgrød', styles: PosStyles(codeTable: PosCodeTable.pc865));`
Setting the code table doesn't seem to help, no matter which code table is chosen.

It fails printing æ ø å, which is wierd since it's literally that example they show inside the latin1 codec.

**Comment by andrey-ushakov** [comment]
Hi,
You have to use `westEur` code table along with `latin1` codec:

`printer.println('blåbærgrød', styles: PosStyles(codeTable: PosCodeTable.westEur));`

For the `pc865` a new codec should be written.

Could you please test it?

Hope it helps!

**Comment by larssn** [comment]
Sorry I should have mentioned that `westEur` was the first thing I tested with. It outputs the exact same string. I've tried setting the code table to various values, just to see if the characters change, which they do not. I know the printer (Epson) supports lots of code tables, as I've previously written my own thermal printer library in javascript for it.

**Comment by andrey-ushakov** [comment]
That's weird...

Here is my test:
```
printer.println('westEur: blåbærgrød', styles: PosStyles(codeTable: PosCodeTable.westEur));
printer.println('pc865: blåbærgrød', styles: PosStyles(codeTable: PosCodeTable.pc865));
printer.println('greek: blåbærgrød', styles: PosStyles(codeTable: PosCodeTable.greek));
```
And the result is:
![testprint](https://hostpic.xyz/files/15639703051648483378.jpg)

Your output is different?
PS: I'm using an Xprinter XP-N160I.

**Comment by larssn** [comment]
Here's my complete code:
```
Printer.connect('192.168.0.99', port: 9100).then((printer) {
   printer.println('blåbærgrød', styles: PosStyles(codeTable: PosCodeTable.westEur));
   printer.cut();
   printer.disconnect();
});
```

It always outputs your second line of printing, for whatever reason.
My printer is an Epson TM-T20, model M249A.

**Comment by andrey-ushakov** [comment]
Could you please post here the output of the following code (consider using the latest library version, a bug in printCodeTable method has just been fixed):

```
printer.println('westEur:');
printer.printCodeTable(codeTable: PosCodeTable.westEur);
printer.println('\n\npc865:');
printer.printCodeTable(codeTable: PosCodeTable.pc865);
```

![codetable](https://hostpic.xyz/files/1563971396876432359.jpg)

**Comment by larssn** [comment]
Here's the commands, and the output as an image:

```
printer.println('westEur:');
printer.printCodeTable(codeTable: PosCodeTable.westEur);
printer.println('\n\npc865:');
printer.printCodeTable(codeTable: PosCodeTable.pc865);
printer.println('\n\n');
printer.println('blåbærgrød', styles: PosStyles(codeTable: PosCodeTable.westEur));
```

![IMG_2213](https://user-images.githubusercontent.com/890725/61795417-ab261980-ae23-11e9-86ea-6d7e36db0821.JPG)

**Comment by larssn** [comment]
Managed to get an `€` printed using:
`printer.sendRaw([0x1b, 0x74, 0x10, 0x80]);`

I set the code page to 1252, and 0x80 is € in this code page.

**Comment by larssn** [comment]
Thanks for listening. I think I'll just write a layer that sends raw data to the printer. 👍

**Comment by andrey-ushakov** [comment]
Hi @larssn ,

Does the issue persist?
Are you using the latest version of the library? 

Btw, I've created a [list of printers tested with this library](https://github.com/andrey-ushakov/esc_pos_printer/blob/master/printers.md). 

May I ask you to add your printer model into the table with any comments (what works and what doesn't)?
It will help me to maintain the library and others to choose the right printer!
Thank you!
