### ISSUE TITLE
posColumn not push long text to new line

### ISSUE THREAD

**Issue by wesleyxiao** [andrey-ushakov/esc_pos_printer#83]
for example i try to print something like

1x.   How do I update values in a       7.80
             database.     
2x    hello world.

but my result coming out is like

1x   How do I update values in a database
7.80

i set 3 posColumn width 2 width 8 width 2
price was been push to new line.

how to make long text when reach to column size overflow text will onto new line

**Comment by andrey-ushakov** [comment]
The issue should be fixed in the latest release. Don't hesitate to reopen the ticket if the problem persists.

**Comment by emmaxCreative** [comment]
I have the same issue.. for me it is not fixed

**Comment by trapeye** [comment]
same still not fix
