### ISSUE TITLE
Unable To Print Japanese Text 

### ISSUE THREAD

**Issue by amibappy** [andrey-ushakov/esc_pos_printer#86]
@andrey-ushakov @ccfiel 

Hi, 
I'm new to flutter. I'm using a MUNBYN  printer.
With the below code I got the output as my attached picture.

`
      final profile = await CapabilityProfile.load();
      final Ticket ticket = Ticket(PaperSize.mm80, profile);
      ticket.setGlobalCodeTable('CP932');
      ticket.printCodeTable();
`
![image0 (1)](https://user-images.githubusercontent.com/13586412/93011949-9469f580-f5d6-11ea-81d3-59553ed9ffe1.jpeg)

It prints Japanese katakana characters with printCodeTable().
But when I try to print it normally it doesn't print it properly.

`
     ticket.text(
       'アメリカ',
       styles: PosStyles(codeTable: 'CP932'),
       containsChinese: true,
     );
`

With the above code, it doesn't print the texts properly. Where am I mistaking? 
I tried containsChinese: false, and some other variations. But couldn't get it to work.

I will be very happy if you can give me some hints or instructions.
Thanks in advance.

**Comment by dariotrombello** [comment]
Same issue but with letters like ä, ö, ü and ß (using CP1252)

**Comment by dariotrombello** [comment]
![20210428_154212](https://user-images.githubusercontent.com/24731809/116414007-6620e980-a838-11eb-8b3b-c01384d6af68.jpg)
![20210428_154123](https://user-images.githubusercontent.com/24731809/116414012-67521680-a838-11eb-999d-03d42d3fc0a1.jpg)
