### ISSUE TITLE
Mixing Chinese and English is a problem

### ISSUE THREAD

**Issue by DesBaiHaoYang** [andrey-ushakov/esc_pos_printer#88]
ticket.text("感觉自己棒棒哒 APP PPAP",containsChinese: true);

![Xnip2020-09-24_11-45-02](https://user-images.githubusercontent.com/42761322/94098573-7c5a6780-fe5b-11ea-8516-0f7f20877806.jpg)

**Comment by andrey-ushakov** [comment]
Hi there,
For me it works as expected. Are you using the latest version of the plugin?
esc_pos_utils: 0.4.9
esc_pos_printer: 3.2.9

**Comment by DesBaiHaoYang** [comment]
sorry ,I use this plugin https://github.com/andrey-ushakov/esc_pos_bluetooth ，The problem appears in the plugin

**Comment by andrey-ushakov** [comment]
Ok, that repo may use an outdated version of `esc_pos_utils`. I didn't have to update to the latest one yet

**Comment by DesBaiHaoYang** [comment]
ok，Looking forward to your code update
